- hosts: webservers
  user: femistone
  become: yes
  become_method: sudo
  gather_facts: yes
  var:
    port: 80
    protocol: http
    ServerName: localhost:80
    DocumentRoot: /var/www

  tasks:
   - name: Ensure that Apache is installed
     yum: name=httpd state=present
     when: ansible_os_family == "RedHat"

   - name: Start Apache Services
     service: name=httpd enabled=yes state=started

   - name: Deploy configuration file
     notify:
       - Restart Apache

  handlers:
      - name: Restart Apache
        service: name=httpd state=restarted

- hosts: dbservers
  become: yes
  user: femistone
  gather_facts: yes
  vars:
    [client]
    port: 3306
    socket: /tmp/mysql.sock
    [mysqld]
    port: 3306
    socket: /tmp/mysql.sock
    key-buffer-size: 16M
    max_allowed_packet: 8M
    [mysqldump]
    quick
    

  tasks:
   - name: Ensure MySQL is installed
     yum: name=mysql-server state=present
   
   - name: start MySQL
     service: name=mysqld state=started
     when: ansible_os_family=="RedHat"  
     
   - name: Deploy mysql configuration
     template: src=/templates/mysql_conf.j2 dest=/etc/mysql/conf/mysql.conf
     notify:
       Restart Mysql
  handler:
    - name: Restart Mysql
      service: name=mysqld state=started
   
   
- hosts: webservers:dbservers
  become: yes
  become_user: femistone

  tasks:
   - name: stop IPTABLES NOW!!!
     service: name=iptables state=stopped
